package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Film;
import ba.unsa.etf.rpr.exceptions.FilmoviException;

import java.util.List;

public class filmoviManager {
    public Film add(Film f) throws FilmoviException {
        if (f.getId() != 0) throw new FilmoviException("Film can not already have an ID. ID is autogenerated.");
        try {
            return DaoFactory.filmDao().add(f);
        } catch (FilmoviException e) {
            throw new FilmoviException(e.getMessage(), e);
        }
    }

    public void delete(int filmId) throws FilmoviException {
        try {
            DaoFactory.filmDao().delete(filmId);
        } catch (FilmoviException e) {
            throw new FilmoviException(e.getMessage(), e);
        }
    }

    public Film update(Film film) throws FilmoviException {
        return DaoFactory.filmDao().update(film);
    }

    public List<Film> getAll() throws FilmoviException {
        return DaoFactory.filmDao().getAll();
    }

    public Film getByIme(String ime) throws FilmoviException {
        return DaoFactory.filmDao().getByIme(ime);
    }

    public List<String> getAllNames() throws FilmoviException {
        return DaoFactory.filmDao().getAllNames();
    }
}
